FROM oryd/kratos:v0.5.5-alpha.1-sqlite as kratos
COPY ./config/kratos.yml /home/ory/.kratos.yml
COPY ./config/identity.schema.json /home/ory/identity.schema.json
COPY ./config/oidc.microsoft.jsonnet /home/ory/oidc.microsoft.jsonnet
#ENV DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
ENV DSN=memory
ENV LOG_LEVEL=trace
EXPOSE 4433:4433
VOLUME /var/lib/sqlite