version: v0.4.6-alpha.1

dsn: memory
    
serve:
  public:
    base_url: https://auth.aiv.liquidstudiobr.com
    cors:
      enabled: true
      allowed_origins:
        - https://auth.aiv.liquidstudiobr.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://kratos.aiv.liquidstudiobr.com/
  whitelisted_return_urls:
    - https://kratos.aiv.liquidstudiobr.com

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: https://kratos.aiv.liquidstudiobr.com/error

    settings:
      ui_url: https://kratos.aiv.liquidstudiobr.com/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: https://kratos.aiv.liquidstudiobr.com/recovery

    verification:
      enabled: true
      ui_url: https://kratos.aiv.liquidstudiobr.com/verify
      after:
        default_browser_return_url: https://kratos.aiv.liquidstudiobr.com/

    logout:
      after:
        default_browser_return_url: https://kratos.aiv.liquidstudiobr.com/auth/login

    login:
      ui_url: https://kratos.aiv.liquidstudiobr.com/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://kratos.aiv.liquidstudiobr.com/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - f7889idf2v2554bn5f42a6tcw

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

session:
  cookie:
    domain: aiv.liquidstudiobr.com
